name: Pull request

on:
    pull_request:
        branches:
            - master
    
jobs:
    slackNotification:
        name: Slack Notification
        runs-on: ubuntu-latest
        steps:
        - uses: rtCamp/action-slack-notify@master
        - name: Slack Notification
            env:
                SLACK_CHANNEL: CiCd
                SLACK_MESSAGE: 'Please review on https://github.com/thongdq/CiCd/pull/${{ env.pull_number}}'
                SLACK_TITLE: 'Pull request'
                SLACK_USERNAME: 'thongdq'
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}